allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  electron-winstaller: false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: false
patchedDependencies:
  nx-electron@22.0.0: patches/nx-electron@22.0.0.patch
