allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  electron-winstaller: false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: false
patchedDependencies:
  nx-electron@22.0.0: patches/nx-electron@22.0.0.patch
overrides:
  '@ngrx/store>@angular/common': $@angular/common
  '@ngrx/store>@angular/core': $@angular/core
  serialize-javascript: ^7.0.7
  dompurify: ^3.4.12
  webpack-dev-server: ^5.2.6
  uuid: ^11.1.1
  esbuild: ^0.28.1
